name: Lock staging deploys during QA

on:
  issues:
    types: [labeled]

jobs:
  lockStagingDeploys:
    if: ${{ github.event.label.name == 'ğŸ” LockCashDeploys ğŸ”' && contains(github.event.issue.labels.*.name, 'StagingDeployCash') && github.actor != 'KirokuAdmin' }}
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.KIROKU_ADMIN_TOKEN }}

      - name: Wait for staging deploys to finish
        uses: ./.github/actions/javascript/awaitStagingDeploys
        with:
          GITHUB_TOKEN: ${{ secrets.KIROKU_ADMIN_TOKEN }}

      - name: Comment in StagingDeployCash to give Applause the ğŸŸ¢ to begin QA
        run: |
          gh issue comment \
            "$(gh issue list --label StagingDeployCash --json number --jq '.[0].number')" \
            --body ":rocket: All staging deploys are complete, please begin QA on version https://github.com/PetrCala/Kiroku/releases/tag/$(< package.json jq -r .version) :rocket:"
        env:
          GITHUB_TOKEN: ${{ secrets.KIROKU_ADMIN_TOKEN }}

      - name: Announce failed workflow in Discord
        if: ${{ failure() }}
        uses: ./.github/actions/composite/announceFailedWorkflowInDiscord
        with:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
